config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # (>) Method directement incluses avec :
  # resources :restaurants, only: [:index, :show]
  # resources :restaurants, except: [:destroy]
  resources :restaurants
  # Lire tous les restaurants
    # get 'restaurants' => "restaurants#index"
  # Lire un restaurant
    # get 'restaurants/:id' => "restaurants#show"
  # Créer un restaurant (2 requêtes)
    # get 'restaurants/new' => "restaurants#new"
    # post 'restaurants' => "restaurants#create"
  # Updater un restaurant
    # get 'restaurants/:id/edit' => "restaurants#edit"
    # patch 'restaurants/:id' => "restaurants#update" 
  # Supprimer un restaurant
    # delete "restaurants/:id" => "restaurants#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    # appeler une méthode avant action
    before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
    # permet d'enlever une ligne redondante pour les méthodes énoncées
    # ici : "@restaurant = Restaurant.find(params[:id])"
    def index
        @restaurants = Restaurant.all
    end
    def show
        # @restaurant = Restaurant.find(params[:id])
    end
    def new
        @restaurant = Restaurant.new
    end
    # on recupere le hash qui correspond à la clé 'restaurant'
    # on peut le faire car on utilise ("restaurant[name]", etc)
    def create
        restaurant = Restaurant.create(restaurant_params)
        redirect_to restaurants_path
    # redirect_to restaurant_path(restaurant)
    end
    def edit
        # @restaurant = Restaurant.find(params[:id])
    end
    def update 
        # @restaurant = Restaurant.find(params[:id])
        @restaurant.update(restaurant_params)
        redirect_to restaurants_path
    end 
    def destroy
        # @restaurant = Restaurant.find(params[:id])
        @restaurant.destroy
        redirect_to restaurants_path
    end

    private
    
    # Quels sont les paramètres autoriser dans le controller 
    
    def restaurant_params
        params.require(:restaurant).permit(:name, :adress, :stars)
    end
    def set_restaurant
        @restaurant = Restaurant.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |f| %>

    <%= f.label :name, "Enter a name"%>
    <%= f.text_field :name %>

    <%= f.label :adress, "Which address ?"%>
    <%= f.text_field :adress %>

    <%= f.label :stars, "How many stars ?"%>
    <%= f.number_field :stars %>
    
    <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Les Restaurants</h1>

<%= link_to "(+) Resto)", new_restaurant_path %>

<% @restaurants.each do |restaurant| %>
    <h2><%= restaurant.name %></h2>
    <p><%= restaurant.adress %>  <%= "*" * restaurant.stars %></p>
    <%= link_to "Voir", restaurant_path(restaurant) %>
    <%= link_to "Delete", restaurant_path(restaurant), method: :delete, 
    data: { confirm: "Are you sure?" } %>
<% end %>

app/views/restaurants/new.html.erb
<%= form_for @restaurant do |f| %>

    <%= f.label :name, "Enter a name"%>
    <%= f.text_field :name %>

    <%= f.label :adress, "Which address ?"%>
    <%= f.text_field :adress %>

    <%= f.label :stars, "How many stars ?"%>
    <%= f.number_field :stars %>
    
    <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.adress %>  <%= "*" * @restaurant.stars %></p>

<%= link_to "Retour", restaurants_path %>